[build]
  command = "npm run build"
  publish = "dist"

# Set the version of Node.js
[build.environment]
  NODE_VERSION = "18.x"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 